### ISSUE TITLE
Cleanup-Test throws an exception if you created the same test file multiple times

### ISSUE THREAD

**Issue by Vananovion** [jonwagner/PSate#11]
I use the following Mock (using PSMock):

Mock Get-ChildItem {
    $testFile = New-TestFile -Name "testfile.exe"
    return $testFile
}

In the tested code, Get-ChildItem is called 2 times and the file is regenerated the second time. However, when PSate leaves the context, Cleanup-Test is called and it attempts to delete the file twice, since it is saved twice in $Context.Items. Naturally, the second attempt throws a "Cannot find path..." exception.

It is of course possible to workaround this, but I would expect PSate to either handle duplicates or call the Remove-Item with -ErrorAction SilentlyContinue .

**Comment by nobodyguy** [comment]
See the PR - https://github.com/jonwagner/PSate/pull/12

**Comment by jonwagner** [comment]
Fixed in v1.0.7
